export { default as FHanhChinh} from './FHanhChinh';
export { default as FPhieuTDDiUngThuoc } from './FPhieuTDDiUngThuoc';
export { default as FLyDoVaoVien } from './FLyDoVaoVien';
export { default as FHoiBenh } from './FHoiBenh';
export { default as FKhamBenh } from './FKhamBenh';
export { default as FChanDoanBanDau } from './FChanDoanBanDau';
export { default as FPhuongPhapDieuTri } from './FPhuongPhapDieuTri';
export { default as FChanDoanKhiRaVien } from './FChanDoanKhiRaVien';
export { default as FTomTatBenhAn } from './FTomTatBenhAn';
export { default as FToDieuTri } from './FToDieuTri';
export { default as FPhieuChamSoc } from './FPhieuChamSoc';
export { default as FPhieuTDChucNangSong } from './FPhieuTDChucNangSong';
export { default as FTinhTrangRaVien } from './FTinhTrangRaVien';
export { default as FHuongDieuTri } from './FHuongDieuTri';
export { default as FPhieuTDTruyenDich } from './FPhieuTDTruyenDich';
export { default as FPhieuCongKhaiThuoc } from './FPhieuCongKhaiThuoc';